### ISSUE TITLE
Uncaught TypeError: this.historyProvider.getChangesSinceCheckpoint is not a function

### ISSUE THREAD

**Issue by awilkins** [atom/teletype#189]
[Enter steps to reproduce:]

1. Install `teletype` and `vim-mode-plus`
2. Share (no need for anyone to join your portal)
3. Enter insert mode
4. Make an edit
5. <kbd>Escape</kbd> - error throws

Unsure whether this is an error down to `teletype` or `vim-mode-plus`, so submitting this to both.

[other issue](https://github.com/t9md/atom-vim-mode-plus/issues/969)

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 1.20.0

### Stack Trace

Uncaught TypeError: this.historyProvider.getChangesSinceCheckpoint is not a function

```
At /usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/text-buffer.js:1017

TypeError: this.historyProvider.getChangesSinceCheckpoint is not a function
    at TextBuffer.module.exports.TextBuffer.getChangesSinceCheckpoint (/usr/share/atom-beta/resources/app/node_modules/text-buffer/lib/text-buffer.js:1017:48)
    at Change.getChangeSinceCheckpoint (/packages/vim-mode-plus/lib/operator-insert.js:25:31)
    at /packages/vim-mode-plus/lib/operator-insert.js:100:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at VimState.activate (/packages/vim-mode-plus/lib/vim-state.js:491:20)
    at /packages/vim-mode-plus/lib/main.js:149:39)
    at HTMLElement.didDispatch (/packages/vim-mode-plus/lib/main.js:198:30)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -1:15.4.0 intentions:highlight (input.hidden-input)
     -1:15.2.0 application:new-window (input.hidden-input)
  7x -0:44.7.0 vim-mode-plus:move-left (input.hidden-input)
     -0:40.1.0 vim-mode-plus:delete-to-last-character-of-line (input.hidden-input)
     -0:36.7.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  3x -0:36 vim-mode-plus:move-down (input.hidden-input)
  4x -0:32.4.0 vim-mode-plus:move-up (input.hidden-input)
     -0:31.1.0 vim-mode-plus:move-down (input.hidden-input)
 22x -0:30.2.0 vim-mode-plus:move-left (input.hidden-input)
     -0:27.1.0 intentions:highlight (input.hidden-input)
     -0:26.9.0 vim-mode-plus:activate-blockwise-visual-mode (input.hidden-input)
  4x -0:26.6.0 vim-mode-plus:move-down (input.hidden-input)
  6x -0:24.4.0 vim-mode-plus:move-right (input.hidden-input)
     -0:21.7.0 vim-mode-plus:change (input.hidden-input)
  2x -0:18 vim-mode-plus:activate-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-ide-ui 0.5.4 
atom-jinja2 0.6.0 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
cucumber-autocomplete 0.7.2 
editorconfig 2.2.2 
ex-mode 0.18.0 
file-icons 2.1.13 
file-types 0.5.5 
floobits 0.32.12 
flow-ide 1.9.0 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
graphviz-preview-plus 1.5.1 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-flowtype 0.17.4 
ide-go 0.4.0 
ide-html 0.4.1 
ide-python 0.3.0 
ide-typescript 0.7.0 
ide-yaml 0.4.1 
intentions 1.1.5 
language-ansible 0.2.1 
language-babel 2.79.0 
language-docker 1.1.8 
language-dot 1.7.0 
language-gherkin 1.0.4 
language-groovy 0.7.0 
language-markdown 0.25.1 
language-nginx 0.8.0 
language-nunjucks 4.1.0 
language-puppet 0.23.0 
language-terraform 0.8.1 
linter 2.2.0 
linter-ansible-linting 1.3.1 
linter-docker 0.2.1 
linter-eslint 8.4.0 
linter-sass-lint 1.8.3 
linter-shellcheck 1.4.6 
linter-terraform-semantics 0.2.0 
linter-terraform-syntax 1.2.1 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
narrow 0.53.2 
nuclide 0.268.0 
regex-railroad-diagram 0.19.4 
teletype 0.1.1 
vim-mode-plus 1.20.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
wordcount 2.10.4 
```

**Comment by as-cii** [comment]
Thanks for the report, @awilkins! ✨ I can reproduce the problem and I am taking a look right now.

**Comment by jasonrudolph** [comment]
@awilkins: Thanks for reporting this issue. We've published a new release (v0.1.1) that should resolve this issue. If you have any trouble, please let us know. :zap:

**Comment by awilkins** [comment]
Looks good here. Legendary fix speed. It is naturally VITAL that all `vim-mode-plus` users can show people just how bitchin' their editing m4dsk1llz are, so good job 👍

**Comment by nathansobo** [comment]
LOL
