### ISSUE TITLE
Uncaught Error: No segment found

### ISSUE THREAD

**Issue by wgrmaceo** [atom/teletype#215]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15r
**OS**: Mac OS X 10.12.6
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.1.2

### Stack Trace

Uncaught Error: No segment found

```
At /Users/maceobonnet/.atom/packages/teletype/node_modules/@atom/teletype-crdt/lib/document-tree.js:77

Error: No segment found
    at DocumentTree.findSegmentContainingPosition (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document-tree.js:77:11)
    at Document.findSegment (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1034:51)
    at Document.getLogicalRange (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:980:74)
    at Document.snapshotFromMarkers (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:907:37)
    at Document.populateHistory (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:56:44)
    at /packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:42:12)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:23:21)
    at Portal.createBufferProxy (/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:114:25)
    at HostPortalBinding.didChangeActiveTextEditor (/packages/teletype/lib/host-portal-binding.js:80:35)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/src/workspace.js:501:30)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.setActiveItem (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/src/pane.js:436:48)
    at Pane.activateItem (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/private/var/folders/60/1_tw4tg16t5bm40vm85pdrnc0000gq/T/AppTranslocation/BA798668-80F6-41BE-8C26-F51D7352214F/d/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:710:25)
```

### Commands

```
     -7:14.7.0 core:paste (input.hidden-input)
     -7:13.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.1.2 
```

**Comment by rsese** [comment]
Do you remember what you were doing at the time of the error @wgrmaceo?  Reported in a couple of other places:

* https://github.com/atom/teletype/issues/224#issuecomment-355651593
* https://github.com/atom/atom/issues/16664
