### ISSUE TITLE
Failed to activate the teletype package

### ISSUE THREAD

**Issue by succeedmr123** [atom/teletype#222]
[Before submitting, please enter steps to reproduce:]

1. ... install teletype package in Atom
2. ...start LearnIDE 3 (Atom packaged with few adjustments for FlatIron School Learn.co curriculum online university)

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.1.3

### Stack Trace

Failed to activate the teletype package

```
At Unexpected identifier

SyntaxError: Unexpected identifier
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/teletype/index.js:1:104)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
     -3:01.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -3:01.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```
teletype 0.1.3 
```

**Comment by 50Wliu** [comment]
Learn IDE is currently based on an Atom version that is too outdated to run teletype.  You'll have to ask them to update to at least Atom 1.22.0.

**Comment by itgoyo** [comment]
thk，it works for me.

**Comment by janderson0000000** [comment]
-3:01.5.0 tree-view:show  #(atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -3:01.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.co
`mpact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)`

**Comment by NikosEfthias** [comment]
I have atom 1.36 and getting the same error @50Wliu

**Comment by Grenadingue** [comment]
Same as @NikosEfthias 

```
Atom    : 1.36.0
Electron: 4.1.4
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
    at Function (<anonymous>)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client_pb.js:12:14)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client_pb.js:5561:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/router.js:2:25)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/router.js:135:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:3:16)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:731:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client.js:5:16)
    at Object.<anonymous> (/home/user/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/teletype-client.js:197:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
```

**Comment by Grenadingue** [comment]
Oops, didn't see you opened a new issue (https://github.com/atom/teletype/issues/446)
