### ISSUE TITLE
Uncaught AssertionError: Target position should not exceed the extent of the given text

### ISSUE THREAD

**Issue by tw-paraxial** [atom/teletype#224]
Not exactly sure how to reproduce this one, but something like:
1. Open atom with a session from last time 
2. Whenever I'd switch tab context to a specific file, this error would be thrown
3. The problem resolved itself when I shut and reopened the same file (but not when I restarted atom)

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.1.3

### Stack Trace

Uncaught AssertionError: Target position should not exceed the extent of the given text

```
At assert.js:85

AssertionError: Target position should not exceed the extent of the given text
    at exports.characterIndexForPosition (/packages/teletype/node_modules/@atom/teletype-crdt/lib/point-helpers.js:71:3)
    at SplitTree.splitSegment (/packages/teletype/node_modules/@atom/teletype-crdt/lib/split-tree.js:74:24)
    at Document.splitSegment (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1028:30)
    at Document.findLocalSegmentBoundary (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1021:19)
    at Document.insert (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:482:32)
    at Document.setTextInRange (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:112:34)
    at Document.populateHistory (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:59:35)
    at /packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:42:12)
    at /packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:23:21)
    at Portal.createBufferProxy (/packages/teletype/node_modules/@atom/teletype-client/lib/portal.js:114:25)
    at HostPortalBinding.didChangeActiveTextEditor (/packages/teletype/lib/host-portal-binding.js:80:35)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:501:30)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:284:26)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:48)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:575:18)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:710:25)
```

### Commands

```
     -0:42.3.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
 24x -0:42.2.0 editor:newline (input.hidden-input)
     -0:20 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:19.4.0 vim-mode-plus:set-count-2 (input.hidden-input)
     -0:19.1.0 vim-mode-plus:set-count-0 (input.hidden-input)
 12x -0:18.2.0 vim-mode-plus:delete (input.hidden-input)
 15x -0:13.9.0 vim-mode-plus:move-up (input.hidden-input)
     -0:12.9.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:11.9.0 ex-mode:open (input.hidden-input)
     -0:11.8.0 core:confirm (input.hidden-input)
  5x -0:11.8.0 blur (input.hidden-input)
     -0:03.5.0 tree-view:toggle (input.hidden-input)
  2x -0:00.1.0 blur (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
ex-mode 0.18.0 
git-blame 1.3.1 
intentions 1.1.5 
language-babel 2.79.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
teletype 0.1.3 
vim-mode-plus 1.20.0 
wordcount 2.10.4 
```

**Comment by as-cii** [comment]
Thanks for the report, @tw-paraxial! It looks like this could be a bug when attempting to store the standard, non-shared history of an Atom buffer into teletype-crdt. It is happening in the same stack trace as #215, so that is interesting.

@tw-paraxial: were you able to reproduce this more than once?

I also wonder if `vim-mode-plus` is altering the contents of the history and making it inconsistent for teletype-crdt's purposes. @t9md: could you help us rule this out? Does `vim-mode-plus` change the `undoStack`/`redoStack` of the history in non-standard ways?

**Comment by tw-paraxial** [comment]
@as-cii I haven't yet been able to reproduce this one, but I'll follow up if I do!

**Comment by t9md** [comment]
@as-cii

> Does vim-mode-plus change the undoStack/redoStack of the history in non-standard ways?

vim-mode-plus(vmp) doesn't modify history once transaction is closed by `editor.groupChangesSinceCheckpoint(checkpoint)`.

But what vmp does is not ordinal way as following
- vmp does not use `editor.transact`, instead vmp manually group editing transaction
  - manually  `editor.createCheckpoint()` then manually close `editor.groupChangesSinceCheckpoint(checkpoint)`.
  - Especially in vmp's `insert-mode`, timing of call to `editor.groupChangesSinceCheckpoint(checkpoint)` can be very late after checkpoint creation. Since when vmp enter `insert-mode`, it create checkpoint, then groupChanges when escaping `insert-mode`.

Not suer this answers your question, feel free to ask more if not clear.

**Comment by t9md** [comment]
btw, what does `Target position should not exceed the extent of the given text` mean?

**Comment by abrooks** [comment]
@as-cii I have a consistent reproducer with this just the latest teletype (0.5.0) and proto-repl (1.4.22) enabled.

```
Error: No segment found
    at DocumentTree.findSegmentContainingPosition (/home/abrooks/.atom/packages/teletype/node_modules/@atom/teletype-crdt/lib/document-tree.js:77:11)
    at Document.findSegment (/home/abrooks/.atom/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1034:51)
    at Document.getLogicalRange (/home/abrooks/.atom/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:979:78)
    at Document.snapshotFromMarkers (/home/abrooks/.atom/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:907:37)
    at Document.createCheckpoint (/home/abrooks/.atom/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:291:23)
    at BufferProxy.createCheckpoint (/home/abrooks/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:125:26)
    at BufferBinding.createCheckpoint (/home/abrooks/.atom/packages/teletype/lib/buffer-binding.js:103:29)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:935:53)
    at TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1811:30)
    at TextEditor.moveCursors (/usr/share/atom/resources/app/src/text-editor.js:2680:23)
    at TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app/src/text-editor.js:2491:23)
    at TextEditorComponent.didMouseDownOnContent (/usr/share/atom/resources/app/src/text-editor-component.js:1810:25)
```

Let me know if I can provide any more information!

**Comment by Arcanemagus** [comment]
@abrooks That's an entirely different stack trace (and thus issue). You should file that as a new issue 😉.

**Comment by abrooks** [comment]
Ack! So it is. I trusted Atom's automatic issue finding. Bleh.
