### ISSUE TITLE
Teletype not installing

### ISSUE THREAD

**Issue by natekfl** [atom/teletype#349]
When installing teletype, both through the gui and by doing `apm install teletype`, it returns the following error:

I am using atom on Windows 10 and have the latest version of Node installed.

```Installing teletype to C:\Users\Nathan Kutzan\.atom\packages failed
C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr
-- (empty)


npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\package.json'
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No description
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No repository field.
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No README data
npm WARN apm-install-dir-118221-4396-195c4ur.q45f1lwhfr No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\Nathan Kutzan\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Nathan Kutzan\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Nathan Kutzan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Nathan Kutzan\\.atom\\.apmrc" "install" "C:\\Users\\NATHAN~1\\AppData\\Local\\Temp\\d-118221-4396-t354s0.2w9971fw29\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at destStatted (C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at destStatted (C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\Nathan Kutzan\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\.staging\event-kit-8dc980ad' -> 'C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\node_modules\teletype\node_modules\event-kit'
npm ERR!     at Error (native) parent: 'teletype' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NATHAN~1\AppData\Local\Temp\apm-install-dir-118221-4396-195c4ur.q45f1lwhfr\npm-debug.log
npm ERR! code 1```

**Comment by natekfl** [comment]
Upon further inspection, it is happening with any package. Should I post this issue on another repo?

**Comment by rsese** [comment]
Ahhh ok thanks for confirming - if you can copy this over to https://github.com/atom/apm that would be great :+1:

**Comment by Delta09** [comment]
I am having the exact same issue, cannot install teletype using `apm install teletype` or even through Atom its self.

**Comment by rsese** [comment]
@Delta09 if you're seeing the exact same error from this issue, please see https://github.com/atom/apm/issues/778 and check if that helps.  If not, please open a new issue in https://github.com/atom/apm and fill out the issue template and we'll take a look.

**Comment by Delta09** [comment]
@rsese Thank you! Had the same issue with Malwarebytes, had to temporarily disable it.
