### ISSUE TITLE
Uncaught NetworkError: Failed to execute 'send' on 'RTCDataChannel': Could not send data

### ISSUE THREAD

**Issue by peejeeman** [atom/teletype#354]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.10.0

### Stack Trace

Uncaught NetworkError: Failed to execute 'send' on 'RTCDataChannel': Could not send data

```
At /Users/PJBenard/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:238

Error: Failed to execute 'send' on 'RTCDataChannel': Could not send data
    at PeerConnection.send (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:235:24)
    at PeerPool.send (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:121:22)
    at StarOverlayNetwork.send (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:310:21)
    at spokes.forEach (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:303:14)
    at Set.forEach (native)
    at StarOverlayNetwork.forwardBroadcast (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:301:17)
    at StarOverlayNetwork.broadcast (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:126:12)
    at Router.notify (/packages/teletype/node_modules/@atom/teletype-client/lib/router.js:34:20)
    at BufferProxy.broadcastUpdate (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:184:17)
    at BufferProxy.revertToCheckpoint (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:144:12)
    at BufferBinding.revertToCheckpoint (/packages/teletype/lib/buffer-binding.js:128:37)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:997:50)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:955:20)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
    at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2708:23)
    at TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2519:23)
    at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1801:25)
```

### Commands

```
  3x -7:12.4.0 core:save (input.hidden-input)
     -4:51.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:23.9.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
  7x -3:20.8.0 core:save (input.hidden-input)
     -3:10.2.0 window:save-all (input.hidden-input)
     -1:24.2.0 core:select-all (input.hidden-input)
     -1:22 core:copy (input.hidden-input)
     -0:52.7.0 core:select-all (input.hidden-input)
     -0:51.7.0 core:copy (input.hidden-input)
     -0:30.9.0 core:select-all (input.hidden-input)
     -0:29.8.0 core:copy (input.hidden-input)
  4x -0:18.1.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.10.0 
```

**Comment by jasonrudolph** [comment]
Thanks for the report! Do you have steps to reproduce, or do you remember what you were doing when you saw the error?

**Comment by CaptainJohnyAppleSeed** [comment]
My team just reproduced this:
1. Open a portal
2. Have at least 1 guest (we've reproduced with both 1 and 2 guests) join the portal.
3. Have 1 guest disconnect (put laptop to sleep) without exiting portal properly
4. Have the host or guest attempt to do *anything* (type, tether, etc)

For every action, the host will get the `RTCData` error.
We've been able to replicate 100% of the time following the above process on teletype v0.11

**Comment by jasonrudolph** [comment]
@CaptainJohnyAppleSeed: I tried to reproduce this issue with Teletype 0.12.0 using the steps in https://github.com/atom/teletype/issues/354#issuecomment-378379581, but I was unable to reproduce it. Are you still able to reproduce this issue?

**Comment by CaptainJohnyAppleSeed** [comment]
@jasonrudolph We've been able to replicate this issue again. After fooling around a bit, I realized that its not that bad if its just 1 guest that disconnects, since after a few minutes, the guest will correctly disconnect and the errors will stop.
We are both running on Teletype `v0.12` with atom `1.25.1` on Mac OS v`10.12.6`.
When I get the chance, I'll see if I can replicate this on Linux and with multiple guests.

![issue_354_1](https://user-images.githubusercontent.com/31418316/38433427-d078b5e0-3998-11e8-9865-42de10a11891.gif)

**Comment by CaptainJohnyAppleSeed** [comment]
We've been doing some more work on this, and we've figured out that the issue occurs specifically when a Guest's computer or laptop goes to **sleep**. Its not an issue if the computer looses internet connection. The latest test was on 2 Mac desktops (Sierra OSx10.12.6) that had never had Atom installed on them.

**Comment by franiis** [comment]
I just had this error in Windows 10. My colleague also is using Windows 10.
Atom: 1.30.0
Teletype: 0.13.3

It occured in similar situation as described here: https://github.com/atom/teletype/issues/354#issuecomment-378379581 but my colleague didn't close laptop. He just closed editor with shared file (we wasn't been able to generate this error again)...

**Comment by BerkhanBerkdemir** [comment]
I can see the same error on Ubuntu 18.04, Atom 1.35.1 and teletype: 0.13.3. There is no other packages other than teletype.

My friend left his pc for sleep, and I switch to atom tab and I saw the bug (which is same with https://github.com/atom/teletype/issues/354#issuecomment-378379581)

<details>
  <summary>Stack Trace</summary>
  
  ```
Error: Failed to execute 'send' on 'RTCDataChannel': Could not send data
    at PeerConnection.send (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:236:24)
    at PeerPool.send (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:121:22)
    at StarOverlayNetwork.send (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:332:21)
    at spokes.forEach (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:325:14)
    at Set.forEach (<anonymous>)
    at StarOverlayNetwork.forwardBroadcast (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:323:17)
    at StarOverlayNetwork.broadcast (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:126:12)
    at Router.notify (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/router.js:34:20)
    at BufferProxy.broadcastUpdate (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:230:17)
    at BufferProxy.broadcastOperations (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:208:10)
    at BufferProxy.revertToCheckpoint (/home/berkhan/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:150:12)
    at BufferBinding.revertToCheckpoint (/home/berkhan/.atom/packages/teletype/lib/buffer-binding.js:138:37)
    at TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app/static/<embedded>:11:492740)
    at TextBuffer.transact (/usr/share/atom/resources/app/static/<embedded>:11:491944)
    at TextEditor.transact (/usr/share/atom/resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (/usr/share/atom/resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (/usr/share/atom/resources/app/static/<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (/usr/share/atom/resources/app/static/<embedded>:11:95794)
  ```
</details>

**Comment by 5892088052** [comment]
> [Enter steps to reproduce:]
> 
> 
> 
> 1. ...
> 
> 2. ...
> 
> 
> 
> **Atom**: 1.25.0 x64
> 
> **Electron**: 1.7.11
> 
> **OS**: Mac OS X 10.13.3
> 
> **Thrown From**: [teletype](https://github.com/atom/teletype) package 0.10.0
> 
> 
> 
> 
> 
> ### Stack Trace
> 
> 
> 
> Uncaught NetworkError: Failed to execute 'send' on 'RTCDataChannel': Could not send data
> 
> 
> 
> ```
> 
> At /Users/PJBenard/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:238
> 
> 
> 
> Error: Failed to execute 'send' on 'RTCDataChannel': Could not send data
> 
>     at PeerConnection.send (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:235:24)
> 
>     at PeerPool.send (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:121:22)
> 
>     at StarOverlayNetwork.send (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:310:21)
> 
>     at spokes.forEach (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:303:14)
> 
>     at Set.forEach (native)
> 
>     at StarOverlayNetwork.forwardBroadcast (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:301:17)
> 
>     at StarOverlayNetwork.broadcast (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:126:12)
> 
>     at Router.notify (/packages/teletype/node_modules/@atom/teletype-client/lib/router.js:34:20)
> 
>     at BufferProxy.broadcastUpdate (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:184:17)
> 
>     at BufferProxy.revertToCheckpoint (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:144:12)
> 
>     at BufferBinding.revertToCheckpoint (/packages/teletype/lib/buffer-binding.js:128:37)
> 
>     at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:997:50)
> 
>     at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:955:20)
> 
>     at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1839:30)
> 
>     at TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2708:23)
> 
>     at TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2519:23)
> 
>     at TextEditorComponent.didMouseDownOnContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1801:25)
> 
> ```
> 
> 
> 
> ### Commands
> 
> 
> 
> ```
> 
>   3x -7:12.4.0 core:save (input.hidden-input)
> 
>      -4:51.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
> 
>      -3:23.9.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
> 
>   7x -3:20.8.0 core:save (input.hidden-input)
> 
>      -3:10.2.0 window:save-all (input.hidden-input)
> 
>      -1:24.2.0 core:select-all (input.hidden-input)
> 
>      -1:22 core:copy (input.hidden-input)
> 
>      -0:52.7.0 core:select-all (input.hidden-input)
> 
>      -0:51.7.0 core:copy (input.hidden-input)
> 
>      -0:30.9.0 core:select-all (input.hidden-input)
> 
>      -0:29.8.0 core:copy (input.hidden-input)
> 
>   4x -0:18.1.0 core:select-all (input.hidden-input)
> 
> ```
> 
> 
> 
> ### Non-Core Packages
> 
> 
> 
> ```
> 
> teletype 0.10.0 
> 
> ```
> 
> 
> 
>
