### ISSUE TITLE
Attempting to join portal failed with error: ref2.file.onDidChange is not a function

### ISSUE THREAD

**Issue by robjac** [atom/teletype#369]
Just got the error this morning on OSX. 

[Enter steps to reproduce:]

1. try to join a colleagues portal
2. bombs out immediately after click.

first attempt error: 
`Attempting to join portal failed with error: ref2.file.onDidChange is not a function
`

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.1

### Stack Trace

Uncaught TypeError: this.resolveConnectionPromise is not a function

```
At /Users/robjac/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:257

TypeError: this.resolveConnectionPromise is not a function
    at StarOverlayNetwork.receiveJoinResponse (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:257:10)
    at StarOverlayNetwork.receive (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:203:12)
    at Function.module.exports.Emitter.simpleDispatch (/packages/teletype/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/packages/teletype/node_modules/event-kit/lib/emitter.js:141:28)
    at PeerPool.didReceiveMessage (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:161:18)
    at PeerConnection.finishReceiving (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:276:10)
    at PeerConnection.receive (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:267:14)
    at RTCDataChannel.channel.onmessage (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:135:47)
```

### Commands

```
  2x -2:55.8.0 core:paste (input.hidden-input)
     -0:25.2.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-neon-color-scheme.theme-pristine-ui.teletype-Authenticated)
     -0:19.2.0 core:paste (input.hidden-input)
     -0:18.2.0 core:select-all (input.hidden-input)
     -0:17.8.0 core:backspace (input.hidden-input)
     -0:13.1.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
accents-ui 1.3.0 
adventurous-syntax 0.2.0 
aesthetic-ui 4.0.0 
an-old-hope-syntax 1.0.4 
angularjs 0.5.3 
animated-cursor 1.1.0 
apex-ui 1.2.0 
atom-beautify 0.32.2 
atom-bulma 0.7.1 
atom-clock 0.1.16 
atom-gooey-syntax 1.0.0 
atom-handlebars 1.3.0 
atom-ide-ui 0.11.1 
atom-jshint 2.0.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-monokai-dark 0.4.0 
atom-pair 2.0.13 
atom-solarized-dark-ui 0.28.1 
atom-sonic 0.3.2 
atom-sonic-pi 0.1.0 
atom-tachyons 1.6.0 
atom-ternjs 0.18.3 
atom-toolbar 0.1.6 
atom-visual-studio-code-ui 1.3.4 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete 0.47.0 
autocomplete-clang 0.11.4 
autocomplete-elixir 1.5.16 
autocomplete-erlang 1.1.2 
autocomplete-glsl 0.2.3 
autocomplete-haskell 1.0.1 
autocomplete-java 1.2.7 
autocomplete-json 5.5.2 
autocomplete-php 0.3.7 
autocomplete-ruby 0.2.8 
autocomplete-ruby-rct 0.1.0 
autoprefixer 3.7.1 
base16-eighties-dark 2.1.1 
brogrammer-syntax 1.0.0 
brogrammer-ui 1.0.0 
browser-plus 0.0.98 
browser-plus-open-new-window 0.0.1 
browser-plus-zoom 0.0.2 
busy-signal 1.4.3 
chameleon-dark-syntax 0.0.5 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
cobalt2-syntax 0.5.3 
color-picker 2.3.0 
custom-folds 1.9.5 
dark-bint-syntax 0.10.0 
dash 1.7.1 
double-tag 1.2.1 
dracula-syntax 2.0.6 
dracula-ui 0.6.0 
elm-format 3.0.0 
elm-instant 2.0.0 
elm-navigator 2.0.0 
elm-snippets 0.1.0 
elmjutsu 8.1.0 
ember-cli-helper 0.17.1 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
enhanced-tabs 1.7.0 
eval-javascript 1.2.0 
Extempore-Atom 0.3.2 
file-icons 2.1.19 
file-watcher 1.2.6 
flex-tool-bar 2.0.2 
floobits 0.32.12 
flow-ide 1.11.0 
font-awesome-snippetset 0.0.6 
fonts 3.0.3 
gibber 0.1.3 
git-status 0.3.4 
git-time-machine 1.5.9 
gl-light-syntax 3.0.0 
gruvbox-plus-syntax 1.3.1 
haskell-ghc-mod 2.2.3 
hey-pane 1.1.0 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-to-elm 0.2.0 
hugs-syntax 1.0.0 
hyperclick 0.1.5 
ide-crystal 0.3.3 
ide-css 0.3.0 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
ide-haskell-hasktags 0.0.15 
ide-haskell-repl 0.8.0 
ide-html 0.4.2 
ide-json 0.2.1 
incremental-search 5.2.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
jQuery 1.2.6 
jquery-snippets 11.0.0 
jslint 1.5.1 
jumpy 4.2.0 
KeyCount 0.2.0 
language-babel 2.84.0 
language-crystal-actual 0.37.2 
language-elixir 0.22.0 
language-elm 1.5.0 
language-glsl 2.0.4 
language-graphql 0.10.1 
language-haml 0.31.0 
language-haskell 1.17.6 
language-ini 1.19.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-supercollider 0.2.1 
language-swift 0.5.0 
language-thrift 1.0.2 
line-count 0.5.0 
line-diff-details 1.9.0 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-clang 4.1.2 
linter-csslint 2.0.0 
linter-elixirc 1.7.0 
linter-elm-make 0.28.3 
linter-erb 1.1.0 
linter-eslint 8.4.1 
linter-glsl 2.1.4 
linter-hlint 2.0.0 
linter-htmlhint 1.4.0 
linter-mixed-indent 1.1.1 
linter-rails-best-practices 0.2.2 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-rust 0.8.5 
linter-sass-lint 1.8.3 
linter-scss-lint 3.1.1 
linter-stylelint 4.2.0 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
linter-xo 0.25.0 
Lucario 2.2.0 
lunar-particle-syntax 0.3.8 
lunar-particle-ui 0.3.13 
material-design-syntax 3.1.2 
miami-nights-syntax 0.3.3 
minimap 4.29.8 
minimap-autohider 1.5.4 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
monokai 0.24.0 
monokai-blackboard 0.3.0 
monokai-dark 1.5.0 
monokai-flat 1.0.1 
monokai-seti 0.9.0 
motepair 0.24.0 
motepair2 0.37.0 
multi-cursor 2.1.5 
neon-color-scheme 1.0.0 
neon-syntax 0.3.7 
nova-atom-syntax 1.5.0 
nova-atom-ui 1.3.0 
nucleus-dark-ui 0.12.3 
nuclide 0.299.0 
nuclide-format-js 0.0.45 
oceanic-next 1.0.0 
oceanic-reef-syntax 0.9.0 
octocat-syntax 2.2.1 
open-recent 5.0.0 
p5xjs-autocomplete 2.3.0 
package-cop 0.2.10 
package-list 0.1.2 
package-switch 0.5.0 
package-sync 1.1.0 
pane-layout-plus 0.7.4 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
prettier-atom 0.53.0 
pristine-ui 1.1.11 
project-colorize 0.3.0 
project-manager 3.3.5 
project-sidebar 1.3.0 
project-view 0.6.2 
pure-syntax 0.3.0 
rails-finder 0.10.0 
rails-snippets 2.18.0 
rails-transporter 1.7.1 
react 0.18.0 
react-es6-snippets 0.3.0 
react-native-snippets 0.3.0 
react-snippets 1.1.0 
recent-projects 0.13.1 
relative-numbers 0.9.0 
robin-hood-syntax 1.0.0 
rubocop-auto-correct 1.5.1 
ruby-solargraph 0.2.0 
script 3.17.3 
scss-media-queries 0.4.0 
scss-snippets 0.6.0 
selector-to-tag 0.4.4 
set-syntax 0.4.0 
seti-syntax 1.1.3 
seti-ui 1.10.0 
seti-ui-red 0.13.0 
SkriptDark-Neon-Syntax 2.1.2 
sort-lines 0.18.0 
spacegray-dark-syntax 0.2.0 
standard-formatter 2.8.0 
standardjs-snippets 2.6.2 
steam-pirate-syntax 0.3.0 
steam-pirate-ui 0.6.1 
Sublime-Style-Column-Selection 1.7.4 
supercollider 0.9.1 
supercopair 0.10.7 
sync-settings 0.8.6 
tab-smart-sort 0.3.0 
teletype 0.13.1 
terminal-syntax 0.1.0 
terminate-syntax 0.3.0 
tidal-autocode 0.6.4 
tidalcycles 0.12.1 
todo-show 2.3.0 
tomorrow 1.0.0 
tomorrow-night-eighties 0.5.0 
tomorrow-night-eighties-syntax 1.0.2 
tool-bar 1.1.7 
tool-bar-almighty 0.8.2 
tree-view-git-status 1.5.0 
ubik-hackerman-syntax 1.10.0 
veda 2.9.0 
vim-mode-plus 1.32.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
zentabs 0.8.9 
```

**Comment by jasonrudolph** [comment]
@robjac: I see that you mention two errors:

> first attempt error:
> `Attempting to join portal failed with error: ref2.file.onDidChange is not a function
> `

...

>> Uncaught TypeError: this.resolveConnectionPromise is not a function
>
> ```
> At /Users/robjac/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:257
>
> TypeError: this.resolveConnectionPromise is not a function
> ```

Can you help me understand the flow of events? I think you're saying that the following things happened:

1. Attempt to join portal
2. Observe error:
    > Attempting to join portal failed with error: ref2.file.onDidChange is not a function
3. Attempt to join portal again
4. Observe different error:
    > Uncaught TypeError: this.resolveConnectionPromise is not a function

Is that right?

**Comment by mrbarletta** [comment]
having the same issue
```
Attempting to join portal failed with error: ref2.file.onDidChange is not a function

Please wait a few moments and try again.
```

let me know if I can provide more information

**Comment by robjac** [comment]
@jasonrudolph that is correct; I haven't attempted to use it again -- but will try once again tomorrow alongside colleagues. I apologize for the delay and vagueness of my first post.

**Comment by jasonrudolph** [comment]
@mrbarletta: Thanks for letting us know that you encountered this issue. Are you consistently seeing this problem? If you restart Atom, do you still observe the problem?

**Comment by mrbarletta** [comment]
Didn't notice but after the error, it still worked fine, the file was open and her avatar shown.

We both upgraded to 26.1, the plugins and restarted, but the message was still popping up.

**Comment by chrispahm** [comment]
Hey there, I'm receiving the same error on Atom 1.28.2 (but also on 1.29 beta 2). It appears consistently and I haven't found a workaround yet. After reading through [#384](https://github.com/atom/teletype/issues/384) I also suspect that the error may be connected to our University network.

**Comment by dionyziz** [comment]
Still getting this error.

**Comment by bennypowers** [comment]
I had this as well as this error https://github.com/atom/spell-check/issues/253

removing a missing locale from spell-check settings Locales field solved the problem in my case

**Comment by ms609** [comment]
Disabling the `wordcount` package seems to have solved the issue for me on Windows 10.

**Comment by xxcosita3czxx** [comment]
same issue, i have no package wordcount
