### ISSUE TITLE
Uncaught Error: Attempted to get identity for non-connected member

### ISSUE THREAD

**Issue by ryry311** [atom/teletype#383]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.3

### Stack Trace

Uncaught Error: Attempted to get identity for non-connected member

```
At /Users/RyanPowell/.atom/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:165

Error: Attempted to get identity for non-connected member
    at process.nextTick (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:161:23)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

### Commands

```
     -2:51.7.0 editor:newline (input.hidden-input)
  2x -2:45.6.0 core:backspace (input.hidden-input)
     -2:17.9.0 core:save (input.hidden-input)
     -0:59.4.0 core:move-right (input.hidden-input)
  2x -0:57.5.0 core:backspace (input.hidden-input)
     -0:48.1.0 core:copy (input.hidden-input)
     -0:47.2.0 core:paste (input.hidden-input)
  2x -0:43.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:36.8.0 core:save (input.hidden-input)
  2x -0:33.5.0 editor:newline (input.hidden-input)
  4x -0:25.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
markdown-pdf 2.2.0 
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if the error is reproducible?

**Comment by ryry311** [comment]
I opened a portal and sent the link to my partner, and every time he tried
to join the portal with that link it created that error. We got it 3 times
in a 10 minute period but haven't tried again since

**Comment by rsese** [comment]
Hmm, did things work ok before but just stopped working that particular day in that 10-minute period?

**Comment by ryry311** [comment]
Yeah things were fine the couple days before

**Comment by asdf23** [comment]
I got this error after installing just this package. I never used it before. The error occurred when someone used the link I sent to connect. I am unsure of the exact steps they took (did they sign into github?... which is what I suspect failed)

**Comment by rsese** [comment]
If you discover exact steps to reproduce let us know @asdf23, that would be super helpful :+1:
