### ISSUE TITLE
Uncaught AssertionError [ERR_ASSERTION]: Target position should not exceed the extent of the give...

### ISSUE THREAD

**Issue by MagicalFries** [atom/teletype#391]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Home
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.3

### Stack Trace

Uncaught AssertionError [ERR_ASSERTION]: Target position should not exceed the extent of the given text

```
At C:\Users\Jasper\AppData\Local\atom\app-1.28.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:980

AssertionError [ERR_ASSERTION]: Target position should not exceed the extent of the given text
    at exports.characterIndexForPosition (/packages/teletype/node_modules/@atom/teletype-crdt/lib/point-helpers.js:71:3)
    at SplitTree.splitSegment (/packages/teletype/node_modules/@atom/teletype-crdt/lib/split-tree.js:74:24)
    at Document.splitSegment (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1055:30)
    at Document.findLocalSegmentBoundary (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1048:19)
    at Document.delete (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:479:24)
    at Document.setTextInRange (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:109:39)
    at BufferProxy.setTextInRange (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:73:38)
    at BufferBinding.pushChange (/packages/teletype/lib/buffer-binding.js:66:24)
    at TextBuffer.module.exports.TextBuffer.applyChange (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:743:22)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:708:29)
    at ~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:682:32
    at TextBuffer.module.exports.TextBuffer.transact (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:973:24)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:680:31)
    at TextEditor.setIndentationForBufferRow (~/AppData/Local/atom/app-1.28.0/resources/app/src/text-editor.js:3719:30)
    at AutoIndent.module.exports.AutoIndent.indentRow (/packages/language-babel/lib/auto-indent.coffee:860:17)
    at AutoIndent.module.exports.AutoIndent.indentUntokenisedLine (/packages/language-babel/lib/auto-indent.coffee:597:15)
    at AutoIndent.module.exports.AutoIndent.indentJSX (/packages/language-babel/lib/auto-indent.coffee:585:12)
    at AutoIndent.module.exports.AutoIndent.didStopChanging (/packages/language-babel/lib/auto-indent.coffee:139:10)
    at /packages/language-babel/lib/auto-indent.coffee:149:66
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1817:26)
    at later (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -9:02.8.0 tabs:split-left (div.title)
     -7:59.1.0 core:confirm (input.hidden-input)
 31x -7:56.2.0 core:move-down (input.hidden-input)
 33x -7:55.7.0 core:move-up (input.hidden-input)
 46x -7:43.5.0 core:move-down (div.package-detail.panels-item)
 37x -7:42.7.0 core:move-up (div.package-detail.panels-item)
 27x -7:42.1.0 core:move-down (div.package-detail.panels-item)
 87x -7:41.2.0 core:move-up (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-terminal 0.8.0 
language-babel 2.85.0 
teletype 0.13.3 
```

this error was created while a friend of mine was typing in my workspace each time he types

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if the error is reproducible?

Not sure if it's the same issue but same error message with a similar-ish stack trace x-ref: https://github.com/atom/teletype/issues/224

**Comment by MagicalFries** [comment]
Whennever we startedd typing in eachother files the error came up it did not matter where we typed in the ffile so whenever my friend typed the error came up i hope it helps



Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Robert Sese <notifications@github.com>
Verzonden: Monday, June 25, 2018 7:08:44 PM
Aan: atom/teletype
CC: MagicalFries; Author
Onderwerp: Re: [atom/teletype] Uncaught AssertionError [ERR_ASSERTION]: Target position should not exceed the extent of the give... (#391)


Thanks for the report! Can you confirm what were you doing at the time of the error and if the error is reproducible?

Not sure if it's the same issue but same error message with a similar-ish stack trace x-ref: #224<https://github.com/atom/teletype/issues/224>

**Comment by rsese** [comment]
Great thanks @MagicalFries - just to confirm one more thing, did you see this behavior just once or do you still see the errors now?

**Comment by jasonrudolph** [comment]
> Not sure if it's the same issue but same error message with a similar-ish stack trace x-ref: #224

I think this is indeed the same problem described in #224, so I'm going to close this issue as a duplicate. Please subscribe to #224 if you'd like to track the status of this bug.

**Comment by jm3** [comment]
Completing a snippet in an HTML doc also caused this Teletype error.
