### ISSUE TITLE
Failed to load the teletype package

### ISSUE THREAD

**Issue by florenciabeber** [atom/teletype#398]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0-d462895
**System**: linux 4.9.0-6-686-pae
**Thrown From**: [teletype](https://github.com/atom/teletype) package, v0.13.3

### Stack Trace

Failed to load the teletype package

```
At /home/fbeber/.atom/packages/teletype/lib/teletype-package.js:1
(function (exports, require, module, __filename, __dirname) { const {TeletypeC
                                                                    ^
Unexpected token {

/home/fbeber/.atom/packages/teletype/lib/teletype-package.js:1
(function (exports, require, module, __filename, __dirname) { const {TeletypeC
                                                                    ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/fbeber/.atom/packages/teletype/index.js:1:87)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
livereload, v0.4.4
teletype, v0.13.3

# Dev
No dev packages
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if the error  is reproducible?

> Atom Version: 0.188.0-d462895

I'm not sure where this version number is from (the current stable release version is 1.28.2), can you confirm if you installed Atom using one of the supported installation methods?

https://flight-manual.atom.io/getting-started/sections/installing-atom/
