### ISSUE TITLE
Uncaught Error: No segment found

### ISSUE THREAD

**Issue by Zinnig** [atom/teletype#421]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: LENOVOYOGA
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.3

### Stack Trace

Uncaught Error: No segment found

```
At C:\Users\felix\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:11

Error: No segment found
    at DocumentTree.findSegmentContainingPosition (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document-tree.js:77:11)
    at Document.findSegment (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1061:51)
    at Document.getLogicalRange (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:1007:74)
    at Document.updateMarkers (/packages/teletype/node_modules/@atom/teletype-crdt/lib/document.js:182:35)
    at BufferProxy.updateMarkers (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:89:38)
    at EditorProxy.updateSelections (/packages/teletype/node_modules/@atom/teletype-client/lib/editor-proxy.js:106:22)
    at EditorBinding.updateSelections (/packages/teletype/lib/editor-binding.js:264:24)
    at marker.onDidChange (/packages/teletype/lib/editor-binding.js:88:14)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:1185469)
    at Emitter.emit (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:1186910)
    at Marker.t.exports.Marker.emitChangeEvent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:67803)
    at Marker.t.exports.Marker.update (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:66857)
    at Marker.t.exports.Marker.setHeadPosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:63016)
    at DisplayMarker.t.exports.DisplayMarker.setHeadBufferPosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:3183236)
    at DisplayMarker.t.exports.DisplayMarker.setHeadScreenPosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:3183468)
    at changePosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:517595)
    at Cursor.changePosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:526020)
    at Cursor.setScreenPosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:517561)
    at moveCursors.n (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:30282)
    at Array.forEach (<anonymous>)
    at transact (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:33144)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:487709)
    at TextEditor.transact (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:95491)
```

### Commands

```
     -1:06.0 core:save (input.hidden-input)
 10x -1:05.7.0 core:move-right (input.hidden-input)
     -1:03.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:03.4.0 editor:newline (input.hidden-input)
  8x -1:01.8.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
  2x -0:46.9.0 core:backspace (input.hidden-input)
     -0:45.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:45.4.0 editor:newline (input.hidden-input)
     -0:41.6.0 intentions:highlight (input.hidden-input)
     -0:41.5.0 core:save (input.hidden-input)
     -0:40 core:move-up (input.hidden-input)
     -0:39.5.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:39.5.0 editor:newline (input.hidden-input)
  3x -0:34.7.0 intentions:highlight (input.hidden-input)
     -0:17.9.0 core:paste (input.hidden-input)
  2x -0:15.2.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.5 
atom-ide-ui 0.13.0 
atom-ternjs 0.18.3 
atom-wrap-in-tag 0.6.0 
autocomplete-modules 2.2.3 
busy-signal 1.4.3 
csscomb 0.3.1 
emmet 2.4.3 
file-icons 2.1.26 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
local-history 4.3.1 
p5xjs-autocomplete 2.3.0 
pigments 0.40.2 
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if the error is reproducible?

x-ref: https://github.com/atom/teletype/issues/215

**Comment by Mojken** [comment]
I just got this same error, was populating a huge (70+) dictionary in an otherwise empty file when suddenly the bottom of the file started throwing errors. I did do some funky C-z and C-y just before, perhaps that's related. Now, my entire file throws errors when I interact with it.

**Comment by rsese** [comment]
Does [clearing saved state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) stop the errors @Mojken?  Note the warning about unsaved data in the documentation.

Also, do you have specific steps to reproduce (along with sample content)?

> was populating a huge (70+) dictionary in an otherwise empty file

When you say "populating", do you mean copy/paste or something else?  And what are the units of 70 here?

**Comment by Mojken** [comment]
Closing down and reopening the file worked, I'd saved recently enough.

I don't know that I do have steps to reproduce, I'm afraid. The dictionary ended up being this:
`onmon = {
    "a": "ㅣ",
    "i": "ㅔ",
    "u": "ㅐ",
    "e": "ㅓ",
    "o": "ㅏ",
    "ka": "키",
    "ki": "케",
    "ku": "캐",
    "ke": "커",
    "ko": "카",
    "kya": "킈",
    "kyu": "쾌",
    "kyo": "콰",
    "ga": "킹",
    "gi": "켕",
    "gu": "캥",
    "ge": "컹",
    "go": "캉",
    "gya": "킝",
    "gyu": "쾡",
    "gyo": "쾅",
    "pa": "피",
    "pi": "페",
    "pu": "패",
    "pe": "퍼",
    "po": "파",
    "pya": "픠",
    "pyu": "퐤",
    "pyo": "퐈",
    "ba": "핑",
    "bi": "펭",
    "bu": "팽",
    "be": "펑",
    "bo": "팡",
    "bya": "픵",
    "byu": "퐹",
    "byo": "퐝",
    "na": "니",
    "ni": "네",
    "nu": "내",
    "ne": "너",
    "no": "나",
    "nya": "늬",
    "nyu": "놰",
    "nyo": "놔",
    "ha": "히",
    "hi": "헤",
    "fu": "빼",
    "he": "허",
    "ho": "하",
    "hya": "희",
    "hyu": "홰",
    "hyo": "화",
    "ma": "미",
    "mi": "메",
    "mu": "매",
    "me": "머",
    "mo": "마",
    "mya": "믜",
    "myu": "뫠",
    "myo": "뫄",
    "ra": "리",
    "ri": "레",
    "ru": "래",
    "re": "러",
    "ro": "라",
    "rya": "릐",
    "ryu": "뢔",
    "ryo": "롸",
    "sha": "씨",
    "shi": "쎄",
    "shu": "쌔",
    "she": "써",
    "sho": "싸",
    "ja": "씽",
    "ji": "쎙",
    "ju": "쌩",
    "je": "썽",
    "jo": "쌍",
    "sa": "시",
    "su": "새",
    "se": "서",
    "so": "사",
    "za": "싱",
    "zu": "생",
    "ze": "성",
    "zo": "상",
    "ta": "티",
    "tsu": "채",
    "te": "터",
    "to": "타",
    "da": "팅",
    "dzu": "챙",
    "de": "텅",
    "do": "탕",
    "cha": "띠",
    "chi": "떼",
    "chu": "때",
    "che": "떠",
    "cho": "따",
    "dja": "띵",
    "dji": "뗑",
    "dju": "땡",
    "dje": "떵",
    "djo": "땅",
    "wa": "비",
    "wi": "베",
    "wu": "배",
    "we": "버",
    "wo": "바",
    "ya": "ㅢ",
    "yi": "ㅞ",
    "yu": "ㅙ",
    "ye": "ㅝ",
    "yo": "ㅘ",
    "n": "ㄴ",
    "ts": "ㅊ",
    "'": "ㅈ"
    }`

Just a silly quick thing I was making. I was pasting in the hangul characters, yeah. I think more likely than that, however, what caused the crash was my C-z'ing, as just before, for some reason, there was a step in the action queue that didn't seem to do anything (C-z once did nothing, twice did what you'd expect). Shortly after, I tried to remove (delete key, not selected) the last entry but couldn't (nothing happened), then the error popped up when I tried to click after that last }. After pressing around a few times, trying to find the border, the error zone slowly started increasing until it covered the entire file and it was unworkable. I noticed that after I'd added that comment, so I am not sure what caused it.

**Comment by rsese** [comment]
> Closing down and reopening the file worked, I'd saved recently enough.

:+1:

> After pressing around a few times, trying to find the border, the error zone slowly started increasing until it covered the entire file and it was unworkable. I noticed that after I'd added that comment, so I am not sure what caused it.

Thanks for the extra details :+1:   If you end up hitting this again and come up with repro steps, please let us know.

**Comment by jm3** [comment]
I got the same Teletype 3x error when completing a snippet in an unsaved HTML file.

**Comment by rsese** [comment]
Is that reproducible for you @jm3 or did you only see the error once?

**Comment by jm3** [comment]
Happened 3 ×.

**Comment by rsese** [comment]
:+1: do you have specific steps to reproduce that you can share?

**Comment by jm3** [comment]
Sorry, I had to uninstall the Teletype plugin, it doesn't seem to be very stable. It threw errors when I saved or basically did anything without even interacting with it. It even continued to throw errors after I disabled the plugin in Atom lol. Had to remove it entirely — no bueno.
