### ISSUE TITLE
Running locally erro

### ISSUE THREAD

**Issue by hanbing5210** [atom/teletype#424]
4 failing

  1) PortalListComponent "before all" hook:
     Error: Error running migrations:

,,
      at TestServer.migrateDatabase (/media/hanbing/linuxs/code/github/teletype/node_modules/@atom/teletype-server/lib/test-server.js:52:13)
      at TestServer.start (/media/hanbing/linuxs/code/github/teletype/node_modules/@atom/teletype-server/lib/test-server.js:21:32)
      at startTestServer (/media/hanbing/linuxs/code/github/teletype/node_modules/@atom/teletype-server/index.js:38:16)
      at Context.<anonymous> (/media/hanbing/linuxs/code/github/teletype/test/portal-list-component.test.js:18:24)
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)

  2) PortalListComponent "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at Context.suiteTeardown (/media/hanbing/linuxs/code/github/teletype/test/portal-list-component.test.js:22:23)
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)

  3) TeletypePackage "before all" hook:
     Error: Error running migrations:

,,
      at TestServer.migrateDatabase (/media/hanbing/linuxs/code/github/teletype/node_modules/@atom/teletype-server/lib/test-server.js:52:13)
      at TestServer.start (/media/hanbing/linuxs/code/github/teletype/node_modules/@atom/teletype-server/lib/test-server.js:21:32)
      at startTestServer (/media/hanbing/linuxs/code/github/teletype/node_modules/@atom/teletype-server/index.js:38:16)
      at Context.<anonymous> (/media/hanbing/linuxs/code/github/teletype/test/teletype-package.test.js:26:24)
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)

  4) TeletypePackage "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at Context.suiteTeardown (/media/hanbing/linuxs/code/github/teletype/test/teletype-package.test.js:38:23)
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)

How do I solve it??

**Comment by hanbing5210** [comment]
atom 1.32.2
node 8.9.3
postgresql 9.6
teketype 0.13.3
Above is the relevant version when I installed it

**Comment by hanbing5210** [comment]
@50Wliu
