### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name pro...

### ISSUE THREAD

**Issue by demoniccc** [atom/teletype#428]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.3

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.

```
At C:\Users\johnp\.atom\packages\teletype\node_modules\etch\lib\render.js:28

Error: Failed to execute 'createElement' on 'Document': The tag name provided ('[object Object]') is not a valid name.
    at render (/packages/teletype/node_modules/etch/lib/render.js:28:26)
    at updateChildren (/packages/teletype/node_modules/etch/lib/patch.js:108:36)
    at patch (/packages/teletype/node_modules/etch/lib/patch.js:18:9)
    at updateSync (/packages/teletype/node_modules/etch/lib/component-helpers.js:116:20)
    at /packages/teletype/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/packages/teletype/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
     -2:33.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -2:26.3.0 command-palette:toggle (input.hidden-input)
     -2:16.4.0 settings-view:install-packages-and-themes (input.hidden-input)
     -1:40.4.0 tree-view:add-file (div.header.list-item.project-root-header)
     -1:37.7.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
  6x -1:34.1.0 core:backspace (input.hidden-input)
     -1:30.6.0 core:confirm (input.hidden-input)
  5x -1:16.4.0 core:undo (div.tool-panel.tree-view)
  2x -1:11.8.0 tree-view:remove (div.tool-panel.tree-view)
     -1:04.3.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:01.0 core:confirm (input.hidden-input)
     -0:49.5.0 tree-view:move (span.name.icon.icon-file-directory)
     -0:43.9.0 core:confirm (input.hidden-input)
     -0:40.6.0 tree-view:add-file (div.header.list-item)
     -0:36.2.0 core:confirm (input.hidden-input)
     -0:14.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
script 3.18.1 
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what were you doing at the time of the error and if the error is reproducible?
