### ISSUE TITLE
Uncaught NetworkError: Failed to execute 'send' on 'RTCDataChannel': Could not send data

### ISSUE THREAD

**Issue by DoughnutDev** [atom/teletype#480]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.4

### Stack Trace

Uncaught NetworkError: Failed to execute 'send' on 'RTCDataChannel': Could not send data

```
At C:\Users\Gunnar Stinson\.atom\packages\teletype\node_modules\@atom\teletype-client\lib\peer-connection.js:239

Error: Failed to execute 'send' on 'RTCDataChannel': Could not send data
    at RTCDataChannel.dataChannel.send (/packages/teletype/node_modules/webrtc-adapter/src/js/common_shim.js:277:36)
    at PeerConnection.send (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-connection.js:236:24)
    at PeerPool.send (/packages/teletype/node_modules/@atom/teletype-client/lib/peer-pool.js:121:22)
    at StarOverlayNetwork.send (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:332:21)
    at spokes.forEach (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:325:14)
    at Set.forEach (<anonymous>)
    at StarOverlayNetwork.forwardBroadcast (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:323:17)
    at StarOverlayNetwork.broadcast (/packages/teletype/node_modules/@atom/teletype-client/lib/star-overlay-network.js:126:12)
    at Router.notify (/packages/teletype/node_modules/@atom/teletype-client/lib/router.js:34:20)
    at BufferProxy.broadcastUpdate (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:230:17)
    at BufferProxy.broadcastOperations (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:208:10)
    at BufferProxy.revertToCheckpoint (/packages/teletype/node_modules/@atom/teletype-client/lib/buffer-proxy.js:150:12)
    at BufferBinding.revertToCheckpoint (/packages/teletype/lib/buffer-binding.js:138:37)
    at TextBuffer.revertToCheckpoint (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:492928)
    at TextBuffer.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:492132)
    at TextEditor.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:24215)
    at TextEditor.moveCursors (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:33112)
    at TextEditor.setCursorScreenPosition (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:30265)
    at TextEditorComponent.didMouseDownOnContent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:96241)
```

### Commands

```
  7x -4:28.5.0 core:undo (input.hidden-input)
  2x -4:22.8.0 core:redo (input.hidden-input)
     -4:18.8.0 core:paste (input.hidden-input)
  5x -1:44.2.0 core:backspace (input.hidden-input)
     -1:39.1.0 core:save (input.hidden-input)
  3x -1:28.9.0 editor:newline (input.hidden-input)
  3x -1:12.7.0 core:backspace (input.hidden-input)
     -1:04.4.0 find-and-replace:show (input.hidden-input)
     -0:51 core:save (input.hidden-input)
     -0:47.7.0 core:copy (input.hidden-input)
     -0:46.9.0 core:paste (input.hidden-input)
     -0:32.3.0 application:new-file (input.hidden-input)
     -0:31.6.0 core:paste (input.hidden-input)
     -0:28.9.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -0:28.9.0 core:paste (input.hidden-input)
  3x -0:18.5.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.13.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what happened before you saw the error?  Did you or someone else connected to the same portal have their computer go to sleep?

x-ref: https://github.com/atom/teletype/issues/354
