### ISSUE TITLE
Failed to activate the teletype package

### ISSUE THREAD

**Issue by NicoLiam** [atom/teletype#487]
**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.4

### Stack Trace

Failed to activate the teletype package

```
At Cannot find module 'etch'

Error: Cannot find module 'etch'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/teletype/lib/site-positions-component.js:1:169)
    at /packages/teletype/lib/site-positions-component.js:94:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/teletype/lib/host-portal-binding.js:5:32)
    at /packages/teletype/lib/host-portal-binding.js:160:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/teletype/lib/portal-binding-manager.js:2:27)
    at /packages/teletype/lib/portal-binding-manager.js:169:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
hey-pane 1.1.2 
Hydrogen 2.9.0 
recovery undefined 
scroll-through-time 0.3.1 
teletype 0.13.4 
zentabs 0.8.9 
```

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [teletype](https://github.com/atom/teletype) package 0.13.4

### Stack Trace

Failed to activate the teletype package

```
At Cannot find module 'etch'

Error: Cannot find module 'etch'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/teletype/lib/site-positions-component.js:1:169)
    at /packages/teletype/lib/site-positions-component.js:94:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/teletype/lib/host-portal-binding.js:5:32)
    at /packages/teletype/lib/host-portal-binding.js:160:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:146745)
    at /packages/teletype/lib/portal-binding-manager.js:2:27)
    at /packages/teletype/lib/portal-binding-manager.js:169:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
hey-pane 1.1.2 
Hydrogen 2.9.0 
recovery undefined 
scroll-through-time 0.3.1 
teletype 0.13.4 
zentabs 0.8.9 
```

**Comment by boc0** [comment]
How did you fix it?
