### ISSUE TITLE
Uncaught TypeError: this.resolveConnectionPromise is not a function

### ISSUE THREAD

**Issue by Ben3eeE** [atom/teletype#51]
1. Bryant closed the connection
1. Robert and I disconnected
1. Bryant Opened a connection
1. Robert was able to join
1. I got a notification that it failed to join
1. I tried to connect again and saw this

![image](https://user-images.githubusercontent.com/1058982/30609883-d977e7d2-9d7c-11e7-8d02-a57e7ca5c540.png)

**Atom**: 1.22.0-dev-006ebc744 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [real-time](https://github.com/atom/real-time) package 0.1.0

### Stack Trace

Uncaught TypeError: this.resolveConnectionPromise is not a function

```
At C:\Users\bene\.atom\packages\real-time\node_modules\@atom\real-time-client\lib\star-overlay-network.js:203

TypeError: this.resolveConnectionPromise is not a function
    at StarOverlayNetwork.receiveConnectionAck (/packages/real-time/node_modules/@atom/real-time-client/lib/star-overlay-network.js:203:10)
    at StarOverlayNetwork.receive (/packages/real-time/node_modules/@atom/real-time-client/lib/star-overlay-network.js:167:12)
    at Function.module.exports.Emitter.simpleDispatch (/packages/real-time/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/packages/real-time/node_modules/event-kit/lib/emitter.js:141:28)
    at PeerPool.didReceiveMessage (/packages/real-time/node_modules/@atom/real-time-client/lib/peer-pool.js:90:18)
    at PeerConnection.finishReceiving (/packages/real-time/node_modules/@atom/real-time-client/lib/peer-connection.js:201:10)
    at PeerConnection.receive (/packages/real-time/node_modules/@atom/real-time-client/lib/peer-connection.js:192:14)
    at RTCDataChannel.channel.onmessage (/packages/real-time/node_modules/@atom/real-time-client/lib/peer-connection.js:105:47)
```

### Commands

```
  3x -7:29.3.0 core:move-down (input.hidden-input)
  4x -7:28.4.0 editor:newline (input.hidden-input)
     -5:04.8.0 tabs:split-right (div.title)
     -2:59.4.0 command-palette:toggle (div.package-detail.panels-item)
     -2:58.1.0 core:confirm (input.hidden-input)
     -2:58.1.0 real-time:join-portal (div.package-detail.panels-item)
     -2:57.7.0 core:paste (input.hidden-input)
     -2:56.9.0 core:undo (input.hidden-input)
     -2:53.7.0 core:confirm (input.hidden-input)
     -2:11.3.0 command-palette:toggle (div.package-detail.panels-item)
     -2:10.5.0 core:confirm (input.hidden-input)
     -2:10.5.0 real-time:join-portal (div.package-detail.panels-item)
     -2:05.3.0 command-palette:toggle (div.package-detail.panels-item)
     -2:04.8.0 core:confirm (input.hidden-input)
     -2:04.8.0 real-time:join-portal (div.package-detail.panels-item)
     -2:04.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-dark-fusion-syntax 2.2.0 
atom-ide-ui 0.1.11 
atom-material-syntax 1.0.6 
atom-material-ui undefined 
autocomplete-emojis 2.5.0 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
chestnut-light-atom-syntax 0.2.1 
color-picker 2.2.5 
editor-stats 0.17.0 
fizzy 0.21.0 
golden-ratio 0.3.0 
hey-pane 1.0.0 
highlight-selected 0.13.1 
honor-altgraph 0.1.0 
intentions 1.1.5 
language-latex 1.1.1 
language-markdown 0.25.1 
latex 0.46.0 
less-than-slash 0.17.0 
linter 2.2.0 
linter-js-standard 4.0.0 
linter-ui-default 1.6.8 
markdown-pdf 1.5.4 
minimap 4.29.6 
minimap-autohider 1.5.3 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
nebula-syntax 0.4.4 
nebula-ui 0.6.0 
no-caffeine-syntax 0.18.1 
nucleus-dark-ui 0.12.3 
pastel-jelly-syntax 0.2.0 
php-cs-fixer 4.1.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
preview-inline 1.4.7 
real-time 0.1.0 
remote-edit 1.9.0 
seti-syntax 1.1.3 
seti-ui 1.9.0 
Sublime-Style-Column-Selection 1.7.4 
tab-title 0.3.5 
toggler 0.3.0 
vim-mode-plus 1.3.3 
zentabs 0.8.8 
```

**Comment by jasonrudolph** [comment]
> I realize this is closed; but should it be? Just got the error this morning on OSX.

Thanks to @robjac for opening https://github.com/atom/teletype/issues/369 to track the most recent incarnation of the "`this.resolveConnectionPromise is not a function`" problem.
