### ISSUE TITLE
I can`t install teletype on my pc(Windows 10)

### ISSUE THREAD

**Issue by Vladka228800** [atom/teletype#640]
Installing “teletype@0.13.4” failed.Hide output…

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://codeload.github.com/atom/teletype/legacy.tar.gz/refs/tags/v0.13.4 failed, reason: connect ECONNREFUSED 127.0.0.1:443
npm ERR!     at ClientRequest.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:223:5)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:406:9)
npm ERR!     at TLSSocket.emit (events.js:223:5)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR!  FetchError: request to https://codeload.github.com/atom/teletype/legacy.tar.gz/refs/tags/v0.13.4 failed, reason: connect ECONNREFUSED 127.0.0.1:443
npm ERR!     at ClientRequest.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:223:5)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:406:9)
npm ERR!     at TLSSocket.emit (events.js:223:5)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
npm ERR!   message: 'request to https://codeload.github.com/atom/teletype/legacy.tar.gz/refs/tags/v0.13.4 failed, reason: connect ECONNREFUSED 127.0.0.1:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://codeload.github.com/atom/teletype/legacy.tar.gz/refs/tags/v0.13.4 failed, reason: connect ECONNREFUSED 127.0.0.1:443\n' +
npm ERR!     '    at ClientRequest.<anonymous> (C:\\Users\\User\\AppData\\Local\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n' +
npm ERR!     '    at ClientRequest.emit (events.js:223:5)\n' +
npm ERR!     '    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n' +
npm ERR!     '    at TLSSocket.emit (events.js:223:5)\n' +
npm ERR!     '    at emitErrorNT (internal/streams/destroy.js:92:8)\n' +
npm ERR!     '    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n' +
npm ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:81:21)'
npm ERR! }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\.atom\.apm\_logs\2021-11-08T15_37_56_666Z-debug.log

**Comment by pjalsGit** [comment]
> reason: connect ECONNREFUSED 127.0.0.1:443
are you using a misconfigured proxy?
